name: Generate icon files from icons.json file

on:
  push:
    branches:
      - icon-update-*
    paths:
      - packages/bezier-icons/icons.json

jobs:
  generate-svg:
    name: Generate icon files from icons.json file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Git Config
        run: |
          git config --global user.email "eng@channel.io"
          git config --global user.name "ch-builder"

      - name: Generate Svg files from icons.json
        run: |
          node packages/bezier-icons/scripts/generate-icon-files.js
          git add .
          git commit -m "feat(bezier-icons): generate icon files from icons.json" || echo "skipped commit due to no update"

      - name: Get Pull request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Add pr description
        run: |
          node packages/bezier-icons/scripts/make-pr-description.js  ${{ secrets.GITHUB_TOKEN }} ${{ steps.pr.outputs.pull_request_number }}
      
      - name: Delete icons.json files
        run: |
          git rm packages/bezier-icons/icons.json
          git commit -m "feat(bezier-icons): remove icons.json"
          git push
